# Generated by Django 5.1.2 on 2025-11-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_details',
            name='rating',
            field=models.CharField(max_length=10),
        ),
    ]
